import { gql } from '@apollo/client';
import * as queries from '@3asoftwares/utils/client';

const queryStrings = {
  // Dashboard
  DASHBOARD_STATS_QUERY: queries.DASHBOARD_STATS_QUERY,
  SALES_ANALYTICS_QUERY: queries.SALES_ANALYTICS_QUERY,

  // User
  GET_USERS_QUERY: queries.GET_USERS_QUERY,
  GET_USER_QUERY: queries.GET_USER_QUERY,
  GET_ME_QUERY: queries.GET_ME_QUERY,
  LOGIN_MUTATION: queries.LOGIN_MUTATION,
  REGISTER_MUTATION: queries.REGISTER_MUTATION,
  GOOGLE_AUTH_MUTATION: queries.GOOGLE_AUTH_MUTATION,
  LOGOUT_MUTATION: queries.LOGOUT_MUTATION,
  UPDATE_USER_ROLE_MUTATION: queries.UPDATE_USER_ROLE_MUTATION,
  DELETE_USER_MUTATION: queries.DELETE_USER_MUTATION,
  SEND_VERIFICATION_EMAIL_MUTATION: queries.SEND_VERIFICATION_EMAIL_MUTATION,
  VERIFY_EMAIL_MUTATION: queries.VERIFY_EMAIL_MUTATION,
  FORGOT_PASSWORD_MUTATION: queries.FORGOT_PASSWORD_MUTATION,
  RESET_PASSWORD_MUTATION: queries.RESET_PASSWORD_MUTATION,
  VALIDATE_RESET_TOKEN_QUERY: queries.VALIDATE_RESET_TOKEN_QUERY,
  UPDATE_PROFILE_MUTATION: queries.UPDATE_PROFILE_MUTATION,

  // Product
  GET_PRODUCTS_QUERY: queries.GET_PRODUCTS_QUERY,
  GET_PRODUCT_QUERY: queries.GET_PRODUCT_QUERY,
  GET_PRODUCTS_BY_SELLER_QUERY: queries.GET_PRODUCTS_BY_SELLER_QUERY,
  CREATE_PRODUCT_MUTATION: queries.CREATE_PRODUCT_MUTATION,
  UPDATE_PRODUCT_MUTATION: queries.UPDATE_PRODUCT_MUTATION,
  DELETE_PRODUCT_MUTATION: queries.DELETE_PRODUCT_MUTATION,

  // Order
  GET_ORDERS_QUERY: queries.GET_ORDERS_QUERY,
  GET_ORDER_QUERY: queries.GET_ORDER_QUERY,
  GET_ORDERS_BY_CUSTOMER_QUERY: queries.GET_ORDERS_BY_CUSTOMER_QUERY,
  CREATE_ORDER_MUTATION: queries.CREATE_ORDER_MUTATION,
  UPDATE_ORDER_STATUS_MUTATION: queries.UPDATE_ORDER_STATUS_MUTATION,
  UPDATE_PAYMENT_STATUS_MUTATION: queries.UPDATE_PAYMENT_STATUS_MUTATION,
  CANCEL_ORDER_MUTATION: queries.CANCEL_ORDER_MUTATION,

  // Coupon
  GET_COUPONS_QUERY: queries.GET_COUPONS_QUERY,
  GET_COUPON_QUERY: queries.GET_COUPON_QUERY,
  VALIDATE_COUPON_QUERY: queries.VALIDATE_COUPON_QUERY,
  CREATE_COUPON_MUTATION: queries.CREATE_COUPON_MUTATION,
  UPDATE_COUPON_MUTATION: queries.UPDATE_COUPON_MUTATION,
  DELETE_COUPON_MUTATION: queries.DELETE_COUPON_MUTATION,
  TOGGLE_COUPON_STATUS_MUTATION: queries.TOGGLE_COUPON_STATUS_MUTATION,

  // Category
  GET_CATEGORIES_QUERY: queries.GET_CATEGORIES_QUERY,
  GET_CATEGORY_QUERY: queries.GET_CATEGORY_QUERY,
  CREATE_CATEGORY_MUTATION: queries.CREATE_CATEGORY_MUTATION,
  UPDATE_CATEGORY_MUTATION: queries.UPDATE_CATEGORY_MUTATION,
  DELETE_CATEGORY_MUTATION: queries.DELETE_CATEGORY_MUTATION,

  // Review
  GET_PRODUCT_REVIEWS_QUERY: queries.GET_PRODUCT_REVIEWS_QUERY,
  CREATE_REVIEW_MUTATION: queries.CREATE_REVIEW_MUTATION,
  MARK_REVIEW_HELPFUL_MUTATION: queries.MARK_REVIEW_HELPFUL_MUTATION,
  DELETE_REVIEW_MUTATION: queries.DELETE_REVIEW_MUTATION,

  // Address
  GET_MY_ADDRESSES_QUERY: queries.GET_MY_ADDRESSES_QUERY,
  ADD_ADDRESS_MUTATION: queries.ADD_ADDRESS_MUTATION,
  UPDATE_ADDRESS_MUTATION: queries.UPDATE_ADDRESS_MUTATION,
  DELETE_ADDRESS_MUTATION: queries.DELETE_ADDRESS_MUTATION,
  SET_DEFAULT_ADDRESS_MUTATION: queries.SET_DEFAULT_ADDRESS_MUTATION,

  // Ticket
  GET_TICKETS_QUERY: queries.GET_TICKETS_QUERY,
  GET_MY_TICKETS_QUERY: queries.GET_MY_TICKETS_QUERY,
  GET_TICKET_QUERY: queries.GET_TICKET_QUERY,
  CREATE_TICKET_MUTATION: queries.CREATE_TICKET_MUTATION,
  ADD_TICKET_COMMENT_MUTATION: queries.ADD_TICKET_COMMENT_MUTATION,
};

type QueryKey = keyof typeof queryStrings;

const gqlQueryCache: Record<string, any> = {};

export const getGqlQuery = (queryName: QueryKey): any => {
  if (!gqlQueryCache[queryName]) {
    gqlQueryCache[queryName] = gql(queryStrings[queryName] as any);
  }
  return gqlQueryCache[queryName];
};

export const GQL_QUERIES = {
  // Dashboard
  DASHBOARD_STATS_QUERY: getGqlQuery('DASHBOARD_STATS_QUERY'),
  SALES_ANALYTICS_QUERY: getGqlQuery('SALES_ANALYTICS_QUERY'),

  // User
  GET_USERS_QUERY: getGqlQuery('GET_USERS_QUERY'),
  GET_USER_QUERY: getGqlQuery('GET_USER_QUERY'),
  GET_ME_QUERY: getGqlQuery('GET_ME_QUERY'),
  LOGIN_MUTATION: getGqlQuery('LOGIN_MUTATION'),
  REGISTER_MUTATION: getGqlQuery('REGISTER_MUTATION'),
  GOOGLE_AUTH_MUTATION: getGqlQuery('GOOGLE_AUTH_MUTATION'),
  LOGOUT_MUTATION: getGqlQuery('LOGOUT_MUTATION'),
  UPDATE_USER_ROLE_MUTATION: getGqlQuery('UPDATE_USER_ROLE_MUTATION'),
  DELETE_USER_MUTATION: getGqlQuery('DELETE_USER_MUTATION'),
  SEND_VERIFICATION_EMAIL_MUTATION: getGqlQuery('SEND_VERIFICATION_EMAIL_MUTATION'),
  VERIFY_EMAIL_MUTATION: getGqlQuery('VERIFY_EMAIL_MUTATION'),
  FORGOT_PASSWORD_MUTATION: getGqlQuery('FORGOT_PASSWORD_MUTATION'),
  RESET_PASSWORD_MUTATION: getGqlQuery('RESET_PASSWORD_MUTATION'),
  VALIDATE_RESET_TOKEN_QUERY: getGqlQuery('VALIDATE_RESET_TOKEN_QUERY'),
  UPDATE_PROFILE_MUTATION: getGqlQuery('UPDATE_PROFILE_MUTATION'),

  // Product
  GET_PRODUCTS_QUERY: getGqlQuery('GET_PRODUCTS_QUERY'),
  GET_PRODUCT_QUERY: getGqlQuery('GET_PRODUCT_QUERY'),
  GET_PRODUCTS_BY_SELLER_QUERY: getGqlQuery('GET_PRODUCTS_BY_SELLER_QUERY'),
  CREATE_PRODUCT_MUTATION: getGqlQuery('CREATE_PRODUCT_MUTATION'),
  UPDATE_PRODUCT_MUTATION: getGqlQuery('UPDATE_PRODUCT_MUTATION'),
  DELETE_PRODUCT_MUTATION: getGqlQuery('DELETE_PRODUCT_MUTATION'),

  // Order
  GET_ORDERS_QUERY: getGqlQuery('GET_ORDERS_QUERY'),
  GET_ORDER_QUERY: getGqlQuery('GET_ORDER_QUERY'),
  GET_ORDERS_BY_CUSTOMER_QUERY: getGqlQuery('GET_ORDERS_BY_CUSTOMER_QUERY'),
  CREATE_ORDER_MUTATION: getGqlQuery('CREATE_ORDER_MUTATION'),
  UPDATE_ORDER_STATUS_MUTATION: getGqlQuery('UPDATE_ORDER_STATUS_MUTATION'),
  UPDATE_PAYMENT_STATUS_MUTATION: getGqlQuery('UPDATE_PAYMENT_STATUS_MUTATION'),
  CANCEL_ORDER_MUTATION: getGqlQuery('CANCEL_ORDER_MUTATION'),

  // Coupon
  GET_COUPONS_QUERY: getGqlQuery('GET_COUPONS_QUERY'),
  GET_COUPON_QUERY: getGqlQuery('GET_COUPON_QUERY'),
  VALIDATE_COUPON_QUERY: getGqlQuery('VALIDATE_COUPON_QUERY'),
  CREATE_COUPON_MUTATION: getGqlQuery('CREATE_COUPON_MUTATION'),
  UPDATE_COUPON_MUTATION: getGqlQuery('UPDATE_COUPON_MUTATION'),
  DELETE_COUPON_MUTATION: getGqlQuery('DELETE_COUPON_MUTATION'),
  TOGGLE_COUPON_STATUS_MUTATION: getGqlQuery('TOGGLE_COUPON_STATUS_MUTATION'),

  // Category
  GET_CATEGORIES_QUERY: getGqlQuery('GET_CATEGORIES_QUERY'),
  GET_CATEGORY_QUERY: getGqlQuery('GET_CATEGORY_QUERY'),
  CREATE_CATEGORY_MUTATION: getGqlQuery('CREATE_CATEGORY_MUTATION'),
  UPDATE_CATEGORY_MUTATION: getGqlQuery('UPDATE_CATEGORY_MUTATION'),
  DELETE_CATEGORY_MUTATION: getGqlQuery('DELETE_CATEGORY_MUTATION'),

  // Review
  GET_PRODUCT_REVIEWS_QUERY: getGqlQuery('GET_PRODUCT_REVIEWS_QUERY'),
  CREATE_REVIEW_MUTATION: getGqlQuery('CREATE_REVIEW_MUTATION'),
  MARK_REVIEW_HELPFUL_MUTATION: getGqlQuery('MARK_REVIEW_HELPFUL_MUTATION'),
  DELETE_REVIEW_MUTATION: getGqlQuery('DELETE_REVIEW_MUTATION'),

  // Address
  GET_MY_ADDRESSES_QUERY: getGqlQuery('GET_MY_ADDRESSES_QUERY'),
  ADD_ADDRESS_MUTATION: getGqlQuery('ADD_ADDRESS_MUTATION'),
  UPDATE_ADDRESS_MUTATION: getGqlQuery('UPDATE_ADDRESS_MUTATION'),
  DELETE_ADDRESS_MUTATION: getGqlQuery('DELETE_ADDRESS_MUTATION'),
  SET_DEFAULT_ADDRESS_MUTATION: getGqlQuery('SET_DEFAULT_ADDRESS_MUTATION'),

  // Ticket
  GET_TICKETS_QUERY: getGqlQuery('GET_TICKETS_QUERY'),
  GET_MY_TICKETS_QUERY: getGqlQuery('GET_MY_TICKETS_QUERY'),
  GET_TICKET_QUERY: getGqlQuery('GET_TICKET_QUERY'),
  CREATE_TICKET_MUTATION: getGqlQuery('CREATE_TICKET_MUTATION'),
  ADD_TICKET_COMMENT_MUTATION: getGqlQuery('ADD_TICKET_COMMENT_MUTATION'),
};
